services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    restart: unless-stopped
    hostname: Jellify
    networks:
      - $NETWORKS
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK: 002
      JELLYFIN_PublishedServerUrl: "https://jelly.$DOMAIN"
    volumes:
      - DATADIR/jellyfin:/config
      - /mnt:/mnt
#      - /mnt/jellyfin/library:/config:rw
    labels:
      - "traefik.enable=true"
      # Router för HTTPS
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jelly.$DOMAIN`)"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.tls.certresolver=cloudflare" # Använder din Cloudflare certifikatutfärdare
      - "traefik.http.routers.jellyfin-secure.service=jellyfin-service" # Namn på tjänsten nedan

      # Definiera tjänsten som routern ska peka på
      - "traefik.http.services.jellyfin-service.loadbalancer.server.port=8096" # Sonarrs interna port

      # Middleware för att lägga till X-Forwarded-Proto header (bra om Sonarr ligger bakom en proxy)
      - "traefik.http.routers.jellyfin-secure.middlewares=sslheader@docker" # Använder samma sslheader middleware som du definierat för Traefik
